version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: sudo pip install pylint
      - run:
          command: pylint --disable=W,C,R ./metrics.py
          name: Lint Fatal Errors

workflows:
  main:
    jobs:
      - lint
