version: 2.1

orbs:
  python: circleci/python@0.2.1
  flake8-orb: wearefair/flake8-orb@0.0.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      # - run:
      #     command: ./manage.py test
      #     name: Test

workflows:
  main:
    jobs:
      - build-and-test
